### ISSUE TITLE
writeStream error when generating highcharts from a Kafka stream in Zeppelin

### ISSUE THREAD

**Issue by PiotrNestor** [knockdata/spark-highcharts#24]
Hi

I'm trying to figure out how to create updating highcharts from a Kafka stream in Zeppelin notebook
The example is based on the spark 'KafkaWordCount.scala' example.

I'm getting:
```
org.apache.spark.sql.AnalysisException: 'writeStream' can be called only on streaming Dataset/DataFrame;
```

Any suggestions how to fix the example code?
What is the correct DataFrame  to provide to highcharts?

The Zeppelin paragraph example:
```
import org.apache.spark.streaming._
import org.apache.spark.streaming.kafka._
import org.apache.spark.sql.types.{StructType, StructField, StringType, IntegerType}
import org.apache.spark.sql.Row

val Array(zkQuorum, group, topics) = Array("localhost:2181", "words_consumer", "words")
val ssc = new StreamingContext(sc, Seconds(1))
//ssc.checkpoint("checkpoint")
val topicMap = topics.split(",").map((_, 1)).toMap
val lines = KafkaUtils.createStream(ssc, zkQuorum, group, topicMap).map(_._2)
val words = lines.flatMap(_.split(" "))
val wordCounts = words.map(x => (x, 1L)).reduceByKeyAndWindow((a:Long,b:Long) => (a + b), Seconds(10), Seconds(10))
wordCounts.print()

val schema = StructType(
    StructField("word", StringType, true) ::
    StructField("count", IntegerType, false) :: Nil)
var df = spark.createDataFrame(sc.emptyRDD[Row], schema)
wordCounts.foreachRDD { rdd => 
    df = df.unionAll(rdd.toDF) 
}
df.show()

import com.knockdata.spark.highcharts._
import com.knockdata.spark.highcharts.model._
val chartParagraph = "20170301-101007_349654791"
val query = highcharts(
  df.seriesCol("words")
    .series("x" -> "word", "y" -> "count")
    .orderBy(col("word")), z, "append")

ssc.start()
ssc.awaitTermination()
```

**Comment by rockie-yang** [comment]
The df is a normal DataFrame. 

It shall be Structured Streaming DataFrame. Try directly on wordCounts

**Comment by PiotrNestor** [comment]
OK. That's correct. I need a structured streaming DataFrame
I've updated the example:
```
import java.sql.Timestamp
import org.apache.spark.sql.functions._

spark.conf.set("spark.sql.streaming.checkpointLocation", "checkpoint")

// Create DataSet representing the stream of input lines from kafka
val lines = spark
            .readStream
            .format("kafka")
            .option("kafka.bootstrap.servers", "localhost:9092")
            .option("subscribe", "words")
            .load()


// Split the lines into words, retaining timestamps
val words = lines
            .selectExpr("CAST(value AS STRING)", "CAST(timestamp AS TIMESTAMP)")
            .as[(String, Timestamp)]
            .flatMap(line => line._1.split(" ").map(word => (word, line._2)))
            .toDF("word", "timestamp")

// Group the data by window and word and compute the count of each group
val windowedCounts = words.groupBy(window($"timestamp", "60 seconds", "60 seconds"), $"word")
            .count()
            .orderBy("window")

import com.knockdata.spark.highcharts._
import com.knockdata.spark.highcharts.model._
val chartParagraph = "20170301-101007_349654791"

val query = highcharts(
  windowedCounts.seriesCol("words")
    .series("x" -> "word", "y" -> "count")
    .orderBy(col("word")), z, "append")

query.awaitTermination()
```

But now I'm getting a different error: 
**Append output mode not supported when there are streaming aggregations on streaming DataFrames/DataSets**
```

import java.sql.Timestamp
import org.apache.spark.sql.functions._
lines: org.apache.spark.sql.DataFrame = [key: binary, value: binary ... 5 more fields]
words: org.apache.spark.sql.DataFrame = [word: string, timestamp: timestamp]
windowedCounts: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [window: struct<start: timestamp, end: timestamp>, word: string ... 1 more field]
import com.knockdata.spark.highcharts._
import com.knockdata.spark.highcharts.model._
chartParagraph: String = 20170301-101007_349654791
org.apache.spark.sql.AnalysisException: Append output mode not supported when there are streaming aggregations on streaming DataFrames/DataSets;;
Sort [window#188 ASC NULLS FIRST], true
+- Aggregate [window#194, word#183], [window#194 AS window#188, word#183, count(1) AS count#193L]
   +- Filter ((timestamp#184 >= window#194.start) && (timestamp#184 < window#194.end))
      +- Expand [List(named_struct(start, ((((CEIL((cast((precisetimestamp(timestamp#184) - 0) as double) / cast(60000000 as double))) + cast(0 as bigint)) - cast(1 as bigint)) * 60000000) + 0), end, (((((CEIL((cast((precisetimestamp(timestamp#184) - 0) as double) / cast(60000000 as double))) + cast(0 as bigint)) - cast(1 as bigint)) * 60000000) + 0) + 60000000)), word#183, timestamp#184), List(named_struct(start, ((((CEIL((cast((precisetimestamp(timestamp#184) - 0) as double) / cast(60000000 as double))) + cast(1 as bigint)) - cast(1 as bigint)) * 60000000) + 0), end, (((((CEIL((cast((precisetimestamp(timestamp#184) - 0) as double) / cast(60000000 as double))) + cast(1 as bigint)) - cast(1 as bigint)) * 60000000) + 0) + 60000000)), word#183, timestamp#184)], [window#194, word#183, timestamp#184]
         +- Project [_1#180 AS word#183, _2#181 AS timestamp#184]
            +- SerializeFromObject [staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._1, true) AS _1#180, staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._2, true) AS _2#181]
               +- MapPartitions <function1>, obj#179: scala.Tuple2
                  +- DeserializeToObject newInstance(class scala.Tuple2), obj#178: scala.Tuple2
                     +- Project [cast(value#154 as string) AS value#168, cast(timestamp#158 as timestamp) AS timestamp#169]
                        +- StreamingRelation DataSource(org.apache.spark.sql.SparkSession@797dace0,kafka,List(),None,List(),None,Map(subscribe -> words, kafka.bootstrap.servers -> localhost:9092),None), kafka, [key#153, value#154, topic#155, partition#156, offset#157L, timestamp#158, timestampType#159]
  at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.org$apache$spark$sql$catalyst$analysis$UnsupportedOperationChecker$$throwError(UnsupportedOperationChecker.scala:196)
  at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.checkForStreaming(UnsupportedOperationChecker.scala:72)
  at org.apache.spark.sql.streaming.StreamingQueryManager.createQuery(StreamingQueryManager.scala:229)
  at org.apache.spark.sql.streaming.StreamingQueryManager.startQuery(StreamingQueryManager.scala:269)
  at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:262)
  at com.knockdata.spark.highcharts.highcharts$.streamingChart(highcharts.scala:52)
  at com.knockdata.spark.highcharts.highcharts$.apply(highcharts.scala:63)
  ... 72 elided
```

**Comment by PiotrNestor** [comment]
An updated example but different problem that I've mentioned before
The first result from the highcharts query is null
This terminates the render operation

The Kafka 'word' topic stream can be generated using the spark command:
```
run-example org.apache.spark.examples.streaming.KafkaWordCountProducer "localhost:9092" words 1 50
```

Example:
```
import java.sql.Timestamp
import org.apache.spark.sql.functions._

spark.conf.set("spark.sql.streaming.checkpointLocation", "checkpoint")

// Create DataSet representing the stream of input lines from kafka
val lines = spark
            .readStream
            .format("kafka")
            .option("kafka.bootstrap.servers", "localhost:9092")
            .option("subscribe", "words")
            .load()


// Split the lines into words, retaining timestamps
val words = lines
            .selectExpr("CAST(value AS STRING)", "CAST(timestamp AS TIMESTAMP)")
            .as[(String, Timestamp)]
            .flatMap(line => line._1.split(" ").map(word => (word, line._2)))
            .toDF("word", "timestamp")

// Group the data by window and word and compute the count of each group
val windowedCounts = words
            .groupBy(window($"timestamp", "10 seconds", "10 seconds"), $"word")
            .count()
            .orderBy("word")

import com.knockdata.spark.highcharts._
import com.knockdata.spark.highcharts.model._

val query = highcharts(
  windowedCounts.seriesCol("word")
    .series("y" -> "count")
    .orderBy(col("word")), z, "complete")

StreamingChart(z)
query.awaitTermination()
```

The error
```
import java.sql.Timestamp
import org.apache.spark.sql.functions._
lines: org.apache.spark.sql.DataFrame = [key: binary, value: binary ... 5 more fields]
words: org.apache.spark.sql.DataFrame = [word: string, timestamp: timestamp]
windowedCounts: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [window: struct<start: timestamp, end: timestamp>, word: string ... 1 more field]
import com.knockdata.spark.highcharts._
import com.knockdata.spark.highcharts.model._
chartParagraph: String = 20170301-101007_349654791
query: org.apache.spark.sql.streaming.StreamingQuery = Streaming Query [id = 900162a7-0daa-42d1-88d9-12d033d34063, runId = 6ad25afa-b67b-474b-85fb-d4ab62d60785] [state = ACTIVE]
null org.apache.spark.sql.streaming.StreamingQueryException: Query [id = 900162a7-0daa-42d1-88d9-12d033d34063, runId = 6ad25afa-b67b-474b-85fb-d4ab62d60785] terminated with exception: null at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches(StreamExecution.scala:284) at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:177) Caused by: java.lang.NullPointerException at org.apache.spark.storage.BlockManagerMaster.getPeers(BlockManagerMaster.scala:102) at org.apache.spark.sql.kafka010.KafkaSource$.org$apache$spark$sql$kafka010$KafkaSource$$getSortedExecutorList(KafkaSource.scala:555) at org.apache.spark.sql.kafka010.KafkaSource.getBatch(KafkaSource.scala:255) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2$$anonfun$apply$6.apply(StreamExecution.scala:452) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2$$anonfun$apply$6.apply(StreamExecution.scala:448) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241) at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241) at scala.collection.Iterator$class.foreach(Iterator.scala:893) at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25) at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241) at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2.apply(StreamExecution.scala:448) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2.apply(StreamExecution.scala:448) at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:262) at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:46) at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch(StreamExecution.scala:447) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1$$anonfun$1.apply$mcV$sp(StreamExecution.scala:255) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1$$anonfun$1.apply(StreamExecution.scala:244) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1$$anonfun$1.apply(StreamExecution.scala:244) at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:262) at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:46) at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1.apply$mcZ$sp(StreamExecution.scala:244) at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:43) at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches(StreamExecution.scala:239) ... 1 more 
```

**Comment by rockie-yang** [comment]
For the `append` and `complete` mode please check. https://github.com/knockdata/spark-highcharts/blob/master/docs/StructureStreaming.md#define-chart

And the checkpoint need be clean when use for new structured streaming
