### ISSUE TITLE
Broke zeppelin spark

### ISSUE THREAD

**Issue by gitfoxi** [knockdata/spark-highcharts#30]
After following setup instructions for Zeppelin, spark is broken.

Someone seemed to have the same problem a while ago here:

https://stackoverflow.com/questions/45509300/zeppelin-0-7-2-org-apache-thrift-transport-ttransportexception-with-spark-and-hi

I'm using the development Zeppelin from git.

zeppelin-interpreter-spark-spark log:

```
ERROR [2017-08-16 07:37:12,600] ({pool-1-thread-5} TThreadPoolServer.java[run]:296) - Error occurred during processing of message.
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:757)
	at com.google.gson.Gson.fromJson(Gson.java:706)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.convert(RemoteInterpreterServer.java:425)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer.interpret(RemoteInterpreterServer.java:243)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Processor$interpret.getResult(RemoteInterpreterService.java:1469)
	at org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Processor$interpret.getResult(RemoteInterpreterService.java:1454)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:285)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
	at com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:306)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:79)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.Gson.fromJson(Gson.java:791)
	... 12 more
```

**Comment by rockie-yang** [comment]
This is most likely due to binary compatibilty issue which requires rebuild spark-highcharts with right spark version. I will check and upgrade to support zeppelin 0.7.2.

**Comment by rockie-yang** [comment]
I have bump the spark-highcharts version to 0.6.5 to support zeppelin 0.7.2 (spark 2.1).
